SpaiR/StrongDMM

README.md

Changes:
* Removed space characters on end of lines.
* Changed `macroses` to `macros`

Spellcheck on README

---

src/main/kotlin/strongdmm/byond/dmm/ColorExtractor.kt

Fixes atoms where colour is set to a hex value with an alpha channel.
In short AWT color's decode does not support colours with alpha, so I am just cutting it out to prevent it from crashing.
This feels a bit hacky and it could probably be implemented correctly with a proper hex colour parser but I am a bit too lazy to do that.

Fix hex colours with transparency causing crashes.

---

src/app/render/brush/brush.go
src/app/render/brush/shader.go

Fixes map not rendering in some cases.
Currently the code assumes uniforms will have specific locations, hardcoded as constants. This seems to not work consistently, especially across platforms, leading to failures when assigning the uniforms from Go code. As a result, the shader doesn't work correctly and the map contents fail to render, displaying only the blue background.
I wasn't sure about the best way to store the uniform indices, so at the moment they are vars in the `brush` package, which means no modification is necessary to code previously using the constants. That said, I'd be happy to move them to a more appropriate location as necessary.

Retrieve uniform indices at runtime using gl.GetUniformIndices

---

src/app/window/window.go

I believe `WindowHint` only applies to newly opened windows, it seems the correct func here is `Show`. Additionally, moved `Show` below `Maximize` - this makes the newly shown window start maximized, preventing any additional animations (from the desktop environment) from playing for the user.

Replace WindowHint with Show

---

src/third_party/sdmmparser/sdmmparser.go

**NOTE:** I don't understand the reasoning behind this specific change, I don't know if this will work across platforms, there's likely a better way.
I'm opening this PR mostly for information, please at the very least check if this also compiles on windows.
The go build is failing for me when building sdmmparser, with linker errors. This links in additional libraries that seem to be necessary on linux.

Fix building on linux by adding missing(?) linker flags

---

src/app/ui/cpwsarea/wsmap/pmap/tilemenu/process.go

Before:
After:
Shift + LMB doesn't select anymore, so the text was incorrect, this just corrects it, and adds text for the deletion option as it was missing it. 
Please check options that are relevant.

Updates shortcut text

---

src/CHANGELOG.md
src/app/ui/cpwsarea/wsmap/pmap/tools.go

When the mouse is over the map window, it is allowed to do map-related hotkeys to work without first having to manually tab in.
resolve #125

Allow window interaction without focus

---

src/CHANGELOG.md
src/app/preferences.go
src/app/preferences_config.go
src/app/prefs/prefs.go
src/app/ui/cpwsarea/wsmap/pmap/pmap.go
src/app/ui/cpwsarea/wsmap/pmap/pquickedit/pquickedit.go
src/app/ui/cpwsarea/wsmap/pmap/tilemenu/process.go
src/app/ui/cpwsarea/wsmap/pmap/tilemenu/tilemenu.go

Added preferences to control Quick Edit menu appearance: it can be shown in the tile context menu or on the map pane.
resolves #117

Preferences for Quick Edit menu appearance 

---

README.md
src/CHANGELOG.md
src/app/render/bucket.go
src/app/ui/cpwsarea/wsmap/pmap/canvas/canvas.go
src/app/ui/cpwsarea/wsmap/pmap/editor/editor.go
src/app/ui/cpwsarea/wsmap/pmap/pmap.go
src/app/ui/cpwsarea/wsmap/pmap/psettings/config.go
src/app/ui/cpwsarea/wsmap/pmap/psettings/psettings.go
src/app/ui/cpwsarea/wsmap/pmap/psettings/screenshot.go
src/util/util.go

Tool to make maps screenshots is available. You can find it in the new settings menu for every map specifically.
To create a screenshot select a directory where you want to create it and press an appropriate button.
Resulted image will respect filtered types and multi-z rendering if enabled.

Added screenshot tool

---

src/platform/glfw.go

Pressing <kbd>Enter</kbd> on the keypad does not behave (and not working at all) like normal one in input fields 😫

Fix: keypad enter does not work

---

docs/README.md
src/third_party/sdmmparser/src/Cargo.toml

Setting this to the current version means you can only build with the very latest version. What it's meant for is to indicate what language features you're using/requiring.
I can verify that the correct value is >= 1.53, since you're using or-patterns. I can also verify that the correct value is <= 1.58.1, since that's what I have available, and it works fine.
1.56 seems like a conservative choice, since that's the 2021 edition, and also when the versioning was introduced. It's very likely that it builds correctly @1.56, since you've introduced almost no changes since then.
(I manually verified that the packages you've bumped versions on have much looser rust-version requirements.)

rust-version is the *minimum required* version.

---

.gitignore
src/app/ui/cpvareditor/collect.go
src/app/ui/cpvareditor/config.go
src/app/ui/cpvareditor/process.go
src/app/ui/cpvareditor/shortcut.go
src/app/ui/cpvareditor/vareditor.go
src/dmapi/dmenv/dme.go
src/dmapi/dmenv/object.go
src/third_party/sdmmparser/sdmmparser.go
src/third_party/sdmmparser/src/environment.rs

- Implement `parent_type` support rather than hardcoding only the built-in parent types
- Forbid editing `const` and `static` variables, like DreamMaker does
- Hide `tmp`, `const`, and `static` variables by default, like DreamMaker does

Implement parent_type and tmp, static, and const vars

---

internal/app/ui/cpwsarea/wsmap/tools/delete.go

Fixes #164
Out of bounds is only allowed for the regular deletion tool which does not use the bound to determine tiles, however it is a problem with the alt function and causes an infinite recursion in findChunkBounds. This makes the out of bounds allowed condition determined by if the alt function is enabled, fixing the issue. Deletion continues to work as expected.

Fix deletion processing out of bounds tiles

---

internal/app/ui/cpwsarea/wsmap/pmap/canvas_camera.go

Fixes #147 
`processCameraZoom()` normally exits when there is no mouseScroll value (by checking `zoomed`, a var set by `processMouseScroll()`).
However, `processMouseScroll()` does not execute if the control is not `Active()`. This means if there is a mouseWheel value on the control and it is exited (no longer active) e.g. by entering the right-click menu, `zoomed` will not be set to false, meaning `processCameraZoom()` will continue to execute.
A simple fix for this is to check if the current control is active in `processCameraZoom()`.

Fix infinite scrolling when the canvas is exited during a scroll

---

internal/dmapi/dmmap/dmmdata/parse.go
internal/dmapi/dmmap/dmmdata/parse_test.go

Fixes #187
StrongDMM ignores whitespace in var blocks, so that varedits like `x     = 2` will turn into `x = 2`. However, it does not account for non-string varedits with whitespace in them, including list(). I decided the best solution was to check if the whitespace was inside a block of `()` within a varedit, so `list()` would allow whitespace inside.
Admittedly this is a patch on solution since it won't actually *correct* strange whitespace within the block, but it does at least consistently keep whatever whitespace is there.
Tested by opening a map with an associative list varedit. The parser kept the whitespace as expected, and saved the map with the same whitespace.
A more robust associative list parsing system that properly parses keys and values should be made, but for now this is …

Fix list whitespace parsing

---

internal/dmapi/dmmap/dmmdata/parse.go
internal/dmapi/dmmap/dmmdata/parse_test.go

PR for #210
closes #210
fixes #209

Ensures whitespace inside text in list pops isn't duplicated

---

internal/app/ui/cpenvironment/environment.go
internal/app/ui/cpenvironment/menu.go

find on map searches by path instead of prefab id
this is good because in the case of ss13 directionals it wouldnt find them if you searched for the parent prefab
https://github.com/SpaiR/StrongDMM/assets/70376633/865b6dfa-838d-46bc-a3f0-3999d8b0f74c

Find on Map searches by path

---

internal/app/ui/cpvareditor/vareditor.go

If the user tries to change a variable to stuff like
list(hi
"im a string
it automatically corrects to
list(hi)
"im a string"

Autocorrect unenclosed strings and lists

---

internal/app/ui/cpwsarea/wsmap/pmap/panel_tools.go
internal/app/ui/cpwsarea/wsmap/tools/fill.go

holding ctrl while using the fill tool now performs a borders-only fill
https://github.com/SpaiR/StrongDMM/assets/70376633/5af166ed-ce82-4acf-a4e5-e10a17ed71f7

Adds border-fill to the border fill tool

---

internal/app/ui/cpwsarea/wsmap/pmap/psettings/screenshot.go

this is my first time using go so bear with me (this took me 20 hours)
Closes #177
Adds a checkbox that allows you to, if ticked screenshot only the selected area
Output:

Adds "Screenshot in Selection" checkbox to screenshot tool

---

internal/dmapi/dmicon/editor.go

Fixes #242. The AMD fix PR contained an error. The icons are still 32x32, there's just a second column.

Fix wide missed icon placeholder

---

README.md

`internal/third_party/sdmmparser/src` does not exist but `third_party/sdmmparser/src` does

correct the path of sdmmparser/src in readme

---

internal/app/ui/cpwsarea/wsmap/pmap/editor/editor.go
internal/app/ui/cpwsarea/wsmap/pmap/panel_tools.go
internal/app/ui/cpwsarea/wsmap/tools/move.go
internal/app/ui/cpwsarea/wsmap/tools/tools.go

https://github.com/SpaiR/StrongDMM/assets/70376633/7dc0bbd3-6814-4424-a926-93f406ab4c2d
holding shift while dragging something with the move tool drags offsets instead

adds pixel drag mode to move tool

---

internal/app/ui/cpenvironment/node.go

This PR makes it so tree nodes will respect the atom's `dir` var when rendering a preview.
Instead of: 
You will now see:

Fix dir being ignored in preview for nodes

---

.github/dependabot.yml
.github/workflows/ci.yml
README.md
Taskfile.yml
docs/CONTRIBUTING.md
go.mod
third_party/sdmmparser/src/Cargo.lock
third_party/sdmmparser/src/Cargo.toml
versioninfo.json

Tweak infra code and documentation

---

internal/app/ui/cpwsarea/wsmap/tools/fill.go

makes the border mode on the fill tool not double place on corners
fixes #327

makes the border mode on the fill tool not double place on corners
